require_relative 'values/heal'
require_relative 'values/damage'
require_relative 'values/drain'
require_relative 'values/gain'
require_relative 'values/effect'
require_relative 'values/skill'
require_relative 'values/magic'
